// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'black': string;
  'blue': string;
  'container': string;
  'gridContainer': string;
  'pad': string;
  'pink': string;
  'title': string;
  'white': string;
}
export const cssExports: CssExports;
export default cssExports;
